/*
 * generated by Xtext 2.25.0
 */
package com.minres.uarchdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UArchDslUiModule extends AbstractUArchDslUiModule {

	public UArchDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
