/*
 * generated by Xtext 2.25.0
 */
package com.minres.uarchdsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.minres.uarchdsl.UArchDslRuntimeModule;
import com.minres.uarchdsl.UArchDslStandaloneSetup;
import com.minres.uarchdsl.ide.UArchDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class UArchDslWebSetup extends UArchDslStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UArchDslRuntimeModule(), new UArchDslIdeModule(), new UArchDslWebModule()));
	}
	
}
