/*
 * generated by Xtext 2.25.0
 */
package com.minres.uarchdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.minres.uarchdsl.UArchDslRuntimeModule;
import com.minres.uarchdsl.UArchDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class UArchDslIdeSetup extends UArchDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UArchDslRuntimeModule(), new UArchDslIdeModule()));
	}
	
}
